### ISSUE TITLE
Misprint on page xiii

### ISSUE THREAD

**Issue by ohld** [DidenkoAndre/GOS_book#18]
Внизу, где ссылка на гитхаб. Нужно "Мы" заменить на "Вы".

**Comment by DidenkoAndre** [comment]
спасибо большое))

**Comment by opomuc** [comment]
Блин, Даня меня опередил...

**Comment by verbagleb** [comment]
До этой страницы мы просто ещё не дошли

**Comment by DidenkoAndre** [comment]
#
