### ISSUE TITLE
Сделать отдельный краткий док

### ISSUE THREAD

**Issue by ohld** [DidenkoAndre/GOS_book#30]
**Что:**
Отдельный pdf файл с формулировками _заглавных теорем_ / _определений_ билета + основная _идея доказательства_ своими словами, кратко. Писать с расчетом на то, что читающий программу и базовые определения знает, то есть не нужно разворачивать каждое определение в теореме. _Это не бомбы, это конспект бомб._
**Зачем:** 
Очень будет полезно всем, популярность обеспечена. 
**Куда:**
Отличным местом для этого документа будет конец книги. Назвать а-ля кратки справочник всего. 
**Примеры:**

>14 Формула Стокса: <написать формулу>. Док: <расписать так-то так-то>

или
>4 Теорема о среднем Ролля: <формулировка>, Лагранжа:  <формулировка>, Коши:  <формулировка>. <Определение дифф функции>.

**Comment by opomuc** [comment]
А вот я считаю это бессмысленным копипастом... В билетах и так уже расписаны все теоремы с доказательствами, зачем их писать еще раз? 
Да и к тому же, изначально, это пособие задумывалось с другой целью

**Comment by ohld** [comment]
Я не прошу переписывать доказательства. Я говорю написать только формулировки и основные идеи. Это поможет при повторении - не нужно будет читать все 150+ страниц. Также это поможет держать все в голове. Перед экзаменом прочитать - самое то.

**Comment by opomuc** [comment]
Формулировки теорем также есть внутри. И на экзамене тебе нужны формулировки не только заглавных теорем, но и всех, которые ты используешь, + определения.
Открываешь заглавие --- выбираешь нужный билет и читаешь :+1:

**Comment by ohld** [comment]
Для этого есть написанные уже билеты. Я же предлагаю ограничиться только формулировками заглавных теорем + заглавных определений.

**Comment by DidenkoAndre** [comment]
Нене, сорри, на такое я не могу позволить себе тратить время, если хочешь, дам права коллаборатора и будешь копипастить туда-сюда. даже техать уметь не надо и тех устанавливать...
