### ISSUE TITLE
Опечатка в билете №7 c.34

### ISSUE THREAD

**Issue by bonlime** [DidenkoAndre/GOS_book#44]
Вместо: 
выполняется условие: ∀M 0 ∈ G ∀ε > 0 ∃δ > 0 : ∀M ∈ G, **|M M 0 |** < δ : |f (M ) − f (M 0 )| < ε.
Должно быть:
выполняется условие: ∀M 0 ∈ G ∀ε > 0 ∃δ > 0 : ∀M ∈ G, **|M - M 0 |** < δ : |f (M ) − f (M 0 )| < ε.
и на пару строк ниже такая же опечатка

**Comment by DidenkoAndre** [comment]
@bonlime А почему Вы считаете это опечаткой?) Как насчет того, что MM_0 это отрезок, соединяющий точки M и M_0, а |MM_0| это его длина? )

Но я не отрицаю, ваш вариант в точности означает тоже самое. Нам Сакбаев на лекциях писал это определение через ...| x - x_0 | < \delta... 

Конкретно в этом билете взят материал с Яковлева, и непохоже, чтобы он просто забыл этот знак минус.
![image](https://user-images.githubusercontent.com/17458671/27337995-a73846dc-55dc-11e7-8005-a88518a30e0e.png)

Возможно, не лучшая система обозначений, обязательно после защиты подумаю над этим.

**Comment by bonlime** [comment]
Видимо и правда кому как удобнее, просто глаз зацепился за непривычное обозначение. Какой вариант оставить без разницы, наверно.
